### ISSUE TITLE
First Successful hit on Apiary

### ISSUE THREAD

**Issue by aWiedebusch** [asaladna/MBB#101]
We need to be able to hit Apiary endpoints for testing the Interfaces to try and break the code.

**Comment by alecsiems1** [comment]
@asaladna @shigaswa 

USE THIS LINK GUI PEOPLE: http://private-9f4a2-pocketgains.apiary-mock.com/

The endpoints go after it. For example, to get the full list of achievements from the apiary example:
*_GET http://private-9f4a2-pocketgains.apiary-mock.com/achievements *_

**Comment by alecsiems1** [comment]
Had first successful hit but not yet from app... working on it.

**Comment by alecsiems1** [comment]
DID IT DROM THE APP WOOP WOOP.

Example code:

```
var apiLink = "http://private-9f4a2-pocketgains.apiary-mock.com"

  $scope.workouts = [ ];

  $http.get(apiLink + "/workout/", { params: {"type": "arms" } })
    .success(function(data) {
        $scope.workouts = data;
        console.log(data);
    })
    .error(function(data) {
        alert("API ERROR at " + apiLink + "\n" + data);
    });
```
