### ISSUE TITLE
Endpoints moved onto the server

### ISSUE THREAD

**Issue by aWiedebusch** [asaladna/MBB#103]
Endpoints for the app's interface to call need to be moved onto the server.  Crucial to being able to test the interface.

**Comment by JustinSuh** [comment]
Moved current endpoints to server for testing purposes

**Comment by alecsiems1** [comment]
@JustinSuh which endpoints are on the server currently??

**Comment by JustinSuh** [comment]
This issue will be updated as time goes on. Google doc is keeping track of endpoints on staging server

**Comment by JustinSuh** [comment]
done
