### ISSUE TITLE
New Achievement Proposal

### ISSUE THREAD

**Issue by alecsiems1** [asaladna/MBB#116]
"Gym Rat": "Create an account on PocketGains!"

This will be a good way to show off the Profile Builder and that we can confirm when an achievement has been completed (one of our big Week 3 goals) all at the same time. It is very good demo material. DB guys ( @aWiedebusch @JustinSuh @wesleysmith26 ) add this one to the DB data please!

**Comment by aWiedebusch** [comment]
Will discuss during meeting. Should just be a simple statement to add it.

**Comment by aWiedebusch** [comment]
Has been added to the main create Achievements Table script.
