### ISSUE TITLE
Change /getSuggestedWorkouts response in Apiary

### ISSUE THREAD

**Issue by alecsiems1** [asaladna/MBB#151]
Right now its this (Not valid JSON):

```
{
            "sets": [
                "set1": 3,
                "set2": 4
            ],
            "reps": [
                "rep1": 12,
                "rep2": 8
            ],
            "weights": [
                "weight1": 10,
                "weight2": 50
            ],
            "titles": [
                "title1": "Bench Press",
                "title2": "Butterfly"
            ]
        }
```

And it now needs to be this....

```
{
    "title1": {
        "sets": 1,
        "reps": 1,
        "weight": 25
    },
    "title2": {
        "sets": 2,
        "reps": 8,
        "weight": 10
    },
    "title3": {
        "sets": 3,
        "reps": 15,
        "weight": 35
    },
    "title4": {
        "sets": 1,
        "reps": 10,
        "weight": 60
    }
}
```

**Comment by aWiedebusch** [comment]
Changed on Apiary

**Comment by alecsiems1** [comment]
I messed up a little. Have the id for the workout be the key to an array of the workouts details ... i.e. change to this...

```
{
    "id1": {
        "title": "Workout title 1",
        "sets": 1,
        "reps": 1,
        "weight": 25
    },
    "id2": {
        "title": "Workout title 2",
        "sets": 1,
        "reps": 1,
        "weight": 25
    },
    "id3": {
        "title": "Workout title 3",
        "sets": 1,
        "reps": 1,
        "weight": 25
    },
    "id4": {
        "title": "Workout title 4",
        "sets": 1,
        "reps": 1,
        "weight": 25
    }
}
```

**Comment by aWiedebusch** [comment]
Changed but kept the id just "id" instead of "id1"...."id4"

**Comment by alecsiems1** [comment]
Can you make each "id" a respective 1,2,3,4?

**Comment by aWiedebusch** [comment]
Wouldn't it rather be like this then?

[
            {"title": "Workout title 1", "sets": 1, "reps": 1, "weight": 25},
            { "title": "Workout title 2", "sets": 2, "reps": 8, "weight": 10},
            {"title": "Workout title 3", "sets": 3, "reps": 15, "weight": 35},
            {"title": "Workout title 4", "sets": 1, "reps": 10, "weight": 60}
]

**Comment by aWiedebusch** [comment]
Or if you wanted the Workout Id it would be like this

{"Workout_id": 1, "title": "Workout title 1", "sets": 1, "reps": 1, "weight": 25},

**Comment by alecsiems1** [comment]
Yeah that's better... call it just "id" instead of "Workout_id" though

**Comment by aWiedebusch** [comment]
workout_id will be what the variable named returned will be.  Still want to change that?

**Comment by alecsiems1** [comment]
yes, still change it

**Comment by aWiedebusch** [comment]
Done on Apiary, Close this if you are satisfied.

**Comment by alecsiems1** [comment]
Perfect. Thanks!
