### ISSUE TITLE
Apiary: /addCompletedWorkout ....can we remove "desc" from POST request?

### ISSUE THREAD

**Issue by alecsiems1** [asaladna/MBB#157]
I don't have the desc on hand at this point in the GUI and it seems unnecesary to include the desc here. If it is needed in the workoutHistory table (which it shouldn't be), you could just pull the desc on the backend with a quick query.

**Comment by aWiedebusch** [comment]
Changed in code and on apiary.

**Comment by alecsiems1** [comment]
it needs to have a "workout_id" param though

**Comment by aWiedebusch** [comment]
I think I fixed it.

**Comment by alecsiems1** [comment]
Responses...
change curly braces to brackets.. JSON syntax thing I guess
Invalid:

```
{
            "Success, information added." 
}
```

Valid

```
[
            "Success, information added." 
]
```

**Comment by aWiedebusch** [comment]
Wait you mean this?

[
            "Success, information added." 
]

**Comment by aWiedebusch** [comment]
All of them?

**Comment by alecsiems1** [comment]
yup... if it's like a one sentence thing

**Comment by alecsiems1** [comment]
use JSONlint.com to make sure all responses are valid JSON

**Comment by aWiedebusch** [comment]
It's fine if it just JSONlint just reformats it in a different way but doesn't yell red things at me right?

**Comment by alecsiems1** [comment]
As long as you see this at the bottom:
![image](https://cloud.githubusercontent.com/assets/3815088/14447502/fab76b2a-0025-11e6-8df7-8c079d987c2e.png)
