### ISSUE TITLE
Create Script for Elevator Speech

### ISSUE THREAD

**Issue by aWiedebusch** [asaladna/MBB#164]
HALP!

**Comment by alecsiems1** [comment]
Alright BOYZ, here's how this is goin down... Any of the profs or TA's for either DB or GUI can ask you AT ANY WAKING MOMENT to give an elevator pitch for PocketGains. We've all been working on the app - we all know how dank it is so this shouldnt be much of a problem! To help us out Im going to write a short script that will act as **AN OUTLINE** for the pitch. **DO NOT MEMORIZE IT WORD FOR WORD**. Tweak it to your liking and make it unique and suave. Anyways, here's the script:

"Many people walk into the gym and have no idea where to start. They want to reach their goal of losing weight or gaining muscle or even just improving their athleticism – yet they don't know how to get there. PocketGains provides a way for users to reach their workout goals by suggesting workouts that will help get them there by taking into account their favorite workouts as well as previous workouts they've done. User's are encouraged to continue to hit the gym via achievements, points, rankings/leaderboards and a simple-to-use interface. PocketGains adapts to YOU; accomplishing your long-sought workout goals has never been this easy."
