### ISSUE TITLE
API NEW ENDPOINT - /getHistory/{user_id}/{timestamp1}/{timestamp2}

### ISSUE THREAD

**Issue by alecsiems1** [asaladna/MBB#184]
Returns the workouts that a user did between timestamp1 and timestamp2... should be pretty straight forward.

**Comment by aWiedebusch** [comment]
Luckily I have that commented out in the routes code. Just changed the endpoint name to /getHistoryRange/{user_id}/{start}/{end} Will close once added to github code.

**Comment by aWiedebusch** [comment]
Willing to change the name to just getHistory though

**Comment by aWiedebusch** [comment]
It's getHistory/{user_id}/{start}/{end}
