### ISSUE TITLE
Create list of Achievements

### ISSUE THREAD

**Issue by alecsiems1** [asaladna/MBB#19]

**Comment by aWiedebusch** [comment]
Let's say 50 is the goal for this one.

**Comment by JustinSuh** [comment]
Achievements will be created that the user can work towards as they continue to work out. A list (in the form of a text file most likely) will be given with 50 achievements (currently) in which we will implement into the app later. More achievements may be added on. Achievements will grant the user rewards for completing them and will create an incentive for people to continue working out while using the app.

**Comment by JustinSuh** [comment]
Thought through potentially how to implement achievements to give them a more engaging feel. Have created different categories for achievements and have very briefly created 5 achievements.

**Comment by JohnDeutsch** [comment]
71 Achievements
- Run for a total of 1 mile: A journey of 1000 miles starts with a single step
- Run for a total of 5 miles: The running man
- Run for a total of 25 miles: Quick Feet
- Run for a total of 50 miles: Hamster on a wheel
- Run for a total of 100 miles: And the bass keeps runnin’ runnin’
- Run for a total of 250 miles: Marathon Runner
- Run for a total of 500 miles: Super Sonic
- Run for a total of 1000 miles: Running around the world
- Use this app for 1 day: Welcome to the club
- Use this app for 2 days: Return customer
- Use this app for 1 week: Daily user
- Use this app for 1 month: Month Man
- Use this app for 6 months: It has been half a year
- Use this app for 1 year: Happy New Year
- Use this app for 2 years: Happy anniversary 
- Use this app for 5 years: You’re still here?
- Lift 10 or more pounds in a leg workout: Wobbly legs
- Lift 30 or more pounds in a leg workout: Double or nothing
- Lift 50 or more pounds in a leg workout: Sore Legs
- Lift 75 or more pounds in a leg workout: Iron Legs
- Lift 100 or more pounds in a leg workout: Work those buns and thighs
- Lift 150 or more pounds in a leg workout: Thunder Thighs
- Lift 200 or more pounds in a leg workout: Steel legs
- Lift 250 or more pounds in a leg workout: Heavyweight champion
- Lift 10 or more pounds in an upper body workout: Gotta start somewhere
- Lift 30 or more pounds in an upper body workout: I can see your muscles
- Lift 50 or more pounds in an upper body workout: Sore arms
- Lift 75 or more pounds in an upper body workout: Bulking up
- Lift 100 or more pounds in an upper body workout: Swole
- Lift 150 or more pounds in an upper body workout: The Rock
- Lift 200 or more pounds in an upper body workout: Superman
- Open this app for the first time: A new life
- Rank within the top 300 of a workout: Top 300
- Rank within the top 150 of a workout: Top 150
- Rank within the top 100 of a workout: Top 100
- Rank within the top 50 of a workout: Top 50
- Rank within the top 10 of a workout: Top 10
- Rank as 1 in a workout: Number 1
- Add 1 friend to your friends list: My first friend
- Add 5 friends to your friends list: Inner circle
- Add 10 friends to your friends list: Buddy buddy
- Add 25 friends to your friends list: The squad
- Add 50 friends to your friends list: Quite a few homies
- Add 100 friends to your friends list: So popular
- Reach level 2: Level up
- Reach level 5: Getting the hang of things
- Reach level 10: Levels and levels
- Reach level 25: Big Gains
- Reach level 50: Attention Getter
- Reach level 100: On top of the world
- Log 1 workout: My first workout
- Log a total of 25 workouts: Workout starter
- Log a total of 50 workouts: Workout Planner
- Log a total of 100 workouts: Workout intellect
- Log a total of 250 workouts: Workout researcher
- Log a total of 500 workouts: Workout Expeditionist
- Log a total of 1000 workouts: Workout Architect
- Do 1 recommended workout: Recommendation
- Do a total of 25 recommended workouts: A helping hand 
- Do a total of 50 recommended workouts: Open to suggestion
- Do a total of 100 recommended workouts:  Constructive Criticism
- Do a total of 250 recommended workouts: Advice follower
- Do a total of 500 recommended workouts: Support from above 
- Do a total of 1000 recommended workouts: Endorsement
- Earn 25 points in 1 week: A few good points
- Earn 50 points in 1 week: Point Getter
- Earn 75 points in 1 week: Free Flowing
- Earn 100 points in 1 week: Drowning in points
- Earn 250 points in 1 week: Show stopper
- Earn 500 points in 1 week: Extreme Training
- Earn 1000 points in 1 week: Hell Week

**Comment by aWiedebusch** [comment]
No friends list achievements will be added for the forseeable future achievements affected are:
Add 1 friend to your friends list: My first friend
Add 5 friends to your friends list: Inner circle
Add 10 friends to your friends list: Buddy buddy
Add 25 friends to your friends list: The squad
Add 50 friends to your friends list: Quite a few homies
Add 100 friends to your friends list: So popular

For a total of 65 achievements
