### ISSUE TITLE
API change request: add "type" to /getHistory/{user_id}/{time_stamp}

### ISSUE THREAD

**Issue by alecsiems1** [asaladna/MBB#190]
Otherwise I have embedded API calls (not good)

**Comment by alecsiems1** [comment]
ALSO - idc if it is only one type out of the several that a workout could potentially have

**Comment by aWiedebusch** [comment]
I got it on my machine. Will update github tomorrow.

**Comment by aWiedebusch** [comment]
On github for both endpoints
