### ISSUE TITLE
Persona for Demo - Details Outlined Here

### ISSUE THREAD

**Issue by alecsiems1** [asaladna/MBB#192]
I want this person to have some specific details in order that the demo is good. Will be commenting for more details but writing this down now so that I don't forget:
- Completed Workouts: The user should have about 5-7 logged ARM & CHEST workouts from 24 to 48 hours back from the presentation time. This way my suggested workouts algorithm will suggest LEG workouts.

**Comment by aWiedebusch** [comment]
Give Gym Rat achievement.

**Comment by aWiedebusch** [comment]
Created the test users in script
