### ISSUE TITLE
ACHIEVEMENT PAGE - design interface for viewing and interacting with various achievements

### ISSUE THREAD

**Issue by alecsiems1** [asaladna/MBB#20]
https://drive.google.com/open?id=1MFMbjo7uQ0yPDy3ARbhHmmkI9QqKXYra7y2T1XvUCkY

Achievements will be a broad list of boolean structured 'tasks' that the user can complete. Some notes about this view:
- Unfinished achievements will appear as icons/badges and defined by earning points in particular categories or completing certain workouts or workout combos
- darkened achievements are not yet completed (although details on how to complete them may be seen)

Example Achievement: **Beast Mode - earn 50 cumulative points from workouts in the Strength category**

**Comment by JohnDeutsch** [comment]
Need to compile a list of all achievements
