### ISSUE TITLE
Create dummy data for DB

### ISSUE THREAD

**Issue by alecsiems1** [asaladna/MBB#26]

**Comment by aWiedebusch** [comment]
The dummy data is assigned to the DB to test the functionality of our app.  This issue is not needed to be done by week 1 but will be needed to be done before testing of our app begins.

**Comment by aWiedebusch** [comment]
I talked with Justin and Wesley and they said they didn't need the dummy data yet. I shall make some data for the tables already set in stone but will need to wait on the additional attributes and updated schema for the analytics and improvements suggested by members from another group.

**Comment by aWiedebusch** [comment]
This includes writing a script that inputs all of the dummy data into the database.

**Comment by aWiedebusch** [comment]
Dummy data scripts have been created for the tables: User, Achievements, Points, and Workouts.

**Comment by aWiedebusch** [comment]
Will test to determine if current scripts are viable.
