### ISSUE TITLE
Initialize staging server with AWS EC2 instance

### ISSUE THREAD

**Issue by alecsiems1** [asaladna/MBB#28]
Ubuntu 14.04 LTS...
IP Address for SSH
Hold on to .pem key from server authentication

**Comment by aWiedebusch** [comment]
This is to set up the staging server with Slim, Apache, MySQL, etc.  to where all tools that are needed are added.

**Comment by aWiedebusch** [comment]
Giving to Justin as weight of issues changed.  Currently both servers have an error when accessing the domain name.

**Comment by JustinSuh** [comment]
Errors have been fixed and both servers are up and running. Info for connecting has been given out to every member.
