### ISSUE TITLE
ACHIEVEMENT PAGE - finalize API call

### ISSUE THREAD

**Issue by alecsiems1** [asaladna/MBB#29]

**Comment by aWiedebusch** [comment]
The Achievements page needs to be able to display what achievements the user has achieved.  So the booleans for each of the achievements of a user needs to be sent to the page.

**Comment by JustinSuh** [comment]
Achievements final product will be updated here once endpoint(s) are finalized.

**Comment by JustinSuh** [comment]
issue will be moved to a new topic
