### ISSUE TITLE
LEADERBOARD PAGE - create categories for sorting leaders

### ISSUE THREAD

**Issue by asaladna** [asaladna/MBB#3]
Come up with a list of category names for which we can score users against.
- Strength
- Endurance
- Agility
- Flexibility 
- etc.

The leaderboards will be broken up based on these categories.

**Comment by JohnDeutsch** [comment]
As of now I think that these categories break everything down in the cleanest way:
- Cardio
- Plyometrics
- Strength
- Flexibility
