### ISSUE TITLE
WORKOUT DASHBOARD - Develop API

### ISSUE THREAD

**Issue by alecsiems1** [asaladna/MBB#30]

**Comment by aWiedebusch** [comment]
Develop actual API code for the Workout Dashboard.  This page needs to be able to get suggested workouts from the Database, post their completed workout information to their workout history, update a favorited workout (and add one), or delete a favorited workout.

**Comment by aWiedebusch** [comment]
This issue will be closed upon a git commit whose name will be posted here.

**Comment by ghost** [comment]
will be replaced
