### ISSUE TITLE
LEADERBOARD PAGE - finalize API call

### ISSUE THREAD

**Issue by alecsiems1** [asaladna/MBB#33]

**Comment by JustinSuh** [comment]
Apiary is done for this.

**Comment by JustinSuh** [comment]
This page will access our points table within our database and display top users within their individual categories. The points database holds individual users' points (for example running points, swimming points, leg points, arm points, etc.) separated by individual workouts. The leaderboards page with display top users for each of those individual categories. Also, the front end side will take the cumulative points by adding all of the users points and show a top leaderboards page that displays users with the most points overall. The final product with be pushed to GitHub. Name of the commit will be posted here.

**Comment by JustinSuh** [comment]
issue wil be moved to a new topic
