### ISSUE TITLE
MAIN DASHBOARD - finalize API call

### ISSUE THREAD

**Issue by alecsiems1** [asaladna/MBB#34]

**Comment by JustinSuh** [comment]
Comment description will come later once I receive a little assistance on exactly how we will develop this. Currently created a rough outline on Apiary.

**Comment by JustinSuh** [comment]
This page will serve as the main menu for the app. It will display points and workouts logged with front end displaying a graphical representation for workouts. This page will access the user, workout history, and points table from within the database to show the relevant data necessary. The user table will be used to display user info (name, goal, etc), the points table will display points, and the workouts logged will show their workouts for the week. Final product will be updated here once endpoint(s) are finalized.

**Comment by JustinSuh** [comment]
topic will move to a new issue
