### ISSUE TITLE
LEADERBOARD PAGE - develop interface

### ISSUE THREAD

**Issue by alecsiems1** [asaladna/MBB#49]
wireframe: https://docs.google.com/drawings/d/1YRFEqDICeV4VNU6jei2cdbRvdEDAuojf9_jB2JdJIeU/edit?usp=sharing

leaderboards.html

**Comment by aWiedebusch** [comment]
Make sure to have a part in the leaderboard to show the user's position in comparison to the top 5.

**Comment by JohnDeutsch** [comment]
The basic interface is done.
