### ISSUE TITLE
RUNNING ACTIVITY PAGE - design interface for starting, doing, completing a run

### ISSUE THREAD

**Issue by asaladna** [asaladna/MBB#5]
https://drive.google.com/open?id=1gokzgkylTEC2I3UzCfkCi4YB5e9B3wV1uge8Fo5lEV0

Show map of route ran and have overall distance, time, and average pace

**Comment by alecsiems1** [comment]
completed iteration 1. https://drive.google.com/open?id=1gokzgkylTEC2I3UzCfkCi4YB5e9B3wV1uge8Fo5lEV0
