### ISSUE TITLE
Setup the access- allow- control

### ISSUE THREAD

**Issue by asaladna** [asaladna/MBB#59]

**Comment by asaladna** [comment]
Needed in order to have an established connection with app and api

**Comment by alecsiems1** [comment]
Assigned to @aWiedebusch - feel free to delegate as necessary

**Comment by aWiedebusch** [comment]
http://stackoverflow.com/questions/7564832/how-to-bypass-access-control-allow-origin

Solution here. Just need to add to our php file headers.
