### ISSUE TITLE
Create table schema for Geolocation Table

### ISSUE THREAD

**Issue by alecsiems1** [asaladna/MBB#60]

**Comment by aWiedebusch** [comment]
I need to look up information on how to implement Geolocation into our app and how I can store that data in the database.  The result will be added to github in the database schema.

**Comment by aWiedebusch** [comment]
Moved to Week 3 milestone since testing other aspects of the app are currently more important.  Will continue to update to complete the database but extending the deadline just in case I don't make it.

**Comment by aWiedebusch** [comment]
Looking like I'm storing longitude and latitude data, I might make a bridge table to allow for the addition of locations based on our discretion.

**Comment by aWiedebusch** [comment]
Will meet with Alec to confirm and I may be a little confused on storing the radius.  New idea, Different geolocations for different excersizes.

**Comment by aWiedebusch** [comment]
I believe this has been done.  Will modify this table if needed once we start testing the geolocation feature.
