### ISSUE TITLE
API - creating an account and authentication (DB)

### ISSUE THREAD

**Issue by asaladna** [asaladna/MBB#7]

**Comment by ghost** [comment]
This page will prompt the user to create an account. The username and email will have to be unique and the password will be hashed and salted after verifying the passwords meet the requirements and match. The final commit for this will be commented below.

**Comment by ghost** [comment]
initial code is complete, some tweaking needed before it will be finalized. Waiting to push commit until we figure out how we want to push to servers

**Comment by ghost** [comment]
commit id 1a08f80 on branch wesley-account-creation
