### ISSUE TITLE
Come up with list of workouts for each category

### ISSUE THREAD

**Issue by alecsiems1** [asaladna/MBB#75]
Categories: Arms, Legs, Chest, Back, Shoulders, Cardio

Additionally, include a description for each workout. This is for the Workouts table that will hold workout_id, name, and description and is the set of all workouts available in our app.

**Comment by alecsiems1** [comment]
## Arms

**Bench Dip** – Face away from bench; place both hands on bench behind you and extend arms with legs in a seated position; bend arms to 90 degree angle then re-extend arms
**Dumbbell Biceps Curl** – Hold dumbbell weights in each hand and keep arms by side with palms facing upwards; curl both arms at the same time up to chest; repeat
**Dip** – Using a dip machine, hold body up with arms extended; dip by bending arms then re-extend
**Dumbbell Kickback** – keep feet staggered and bend over slightly with dumbbell in each hand and arms extended slightly behind body; bring dumbbells to chest then re-extend arms
**Bench Fly** – Lay down on bench and extend arms straight above body with dumbbell in each hand; slowly lower arms to each side while keeping arms extended until dumbbells are chest-level; raise arms back to above body

**Comment by alecsiems1** [comment]
This sprint (3) is using Apiary so this was a low priority compared to all the other work I've been doing. Pushing to Week 4 and assigning to @shigaswa

**Comment by JohnDeutsch** [comment]
https://docs.google.com/spreadsheets/d/1u0ymcOMNdVgZS1qmvp6JoxiBvZnYG8_vCHbpmTXqbzA/edit#gid=0

This spreadsheet isn't organized in any particular way, although the first category listed for each exercise is the main category/muscle group. Most of the descriptions used are from http://www.bodybuilding.com/

**Comment by JohnDeutsch** [comment]
There are 261 workouts listed.
