### ISSUE TITLE
Develop DB Schema

### ISSUE THREAD

**Issue by aWiedebusch** [asaladna/MBB#8]
Creating the database schema for our app.  What tables and attributes those tables have will be posted here.  (link to picture of database schema and .sql script will posted here and on repo)

**Comment by aWiedebusch** [comment]
3/17/2016  Met with Alec to discuss direction of app and app features to iron down the API and pages. Bringing me one step closer to creating the DB Schema.

**Comment by JustinSuh** [comment]
Will be meeting with DB members to discuss this further to nail it down. Created a very rough sketch of what the schema will look like.

**Comment by JustinSuh** [comment]
Developed DB schema slightly more. Edited original one to reflect info that was given to me.

**Comment by aWiedebusch** [comment]
Drew a rough draft of our ER Diagram in class, final ER Diagram will be done on vertabelo for ease of database creation and neatness.
[DB3330-ER Diagram.pdf](https://github.com/asaladna/MBB/files/183258/DB3330-ER.Diagram.pdf)

**Comment by aWiedebusch** [comment]
Rough Database Schema created.  Will update it as I learn about caching and geolocation.

**Comment by aWiedebusch** [comment]
Will close this issue with a diagram of the current database schema in vertabelo.  The next issues related to the database will be independent issues.

**Comment by aWiedebusch** [comment]
![database](https://cloud.githubusercontent.com/assets/13954807/13972520/808b2b20-f067-11e5-929e-13b0a04aa746.png)
