### ISSUE TITLE
Profile Builder - Develop Interface

### ISSUE THREAD

**Issue by alecsiems1** [asaladna/MBB#96]
Using these mockups: https://docs.google.com/drawings/d/1HJgzlLAZKeQsnIZKJkE8D8lpOK4ken25na8JU-JE3cg/edit?usp=sharing

**Comment by alecsiems1** [comment]
@aWiedebusch I may deprecate the selecting of favorite workouts to one of each so that the interface for initially opening the app isn't so involved, thoughts? This will also be cleaner to have the 5 categories on one pane rather than one pane for each of the 5 categories - much easier from a developing standpoint. This would affect the Apiary response for /createNewUser

**Comment by aWiedebusch** [comment]
Ya I'll meet with you and propose some responses.

**Comment by alecsiems1** [comment]
Finished! Connected to apiary API also
